
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HumanVerification?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}       # Uses DB_USERNAME env var, defaults to root
    password: ${DB_PASSWORD:A10102004a} # Uses DB_PASSWORD env var, defaults to your password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#java mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: broilzzz09@gmail.com
    password: wufl bwlu cbst anld
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# AWS Configuration
aws:
  sqs:
    request-queue-url: ${AWS_SQS_REQUEST_QUEUE_URL:https://sqs.ap-south-1.amazonaws.com/241789449449/ApprovalRoundSqs}
    dlq-url: ${AWS_SQS_DLQ_URL:https://sqs.ap-south-1.amazonaws.com/241789449449/ApprovalRoundDlq}
    callback-queue-url: ${AWS_SQS_CALLBACK_URL:https://sqs.ap-south-1.amazonaws.com/241789449449/CallbackSqs}
    callback-dlq-url: ${AWS_SQS_CALLBACK_DLQ_URL:https://sqs.ap-south-1.amazonaws.com/241789449449/CallBackSqsDlq}

  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:lyzr-hackathon-attachment-bucket}

# Application Configuration
app:
  backoff:
    initial-delay-seconds: 120   # 2 minutes delay
    max-delay-seconds: 7200      # Maximum delay between retries (2 hours)
    multiplier: 2.5              # Exponential backoff multiplier (2min -> 5min -> 12.5min -> 31.25min)